# Generated by Django 4.0.6 on 2022-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_alter_donation_zip_code_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='taken_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna'), (1, 'fundacja')], default=1),
        ),
    ]
