# Generated by Django 4.0.6 on 2022-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0005_alter_donation_institution_alter_donation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
